Class {
	#name : #TPChatMember,
	#superclass : #TPObject,
	#instVars : [
		'user',
		'status',
		'custom_title',
		'is_anonymous',
		'can_be_edited',
		'can_post_message',
		'can_edit_messages',
		'can_delete_messages',
		'can_restrict_members',
		'can_promote_members',
		'can_change_info',
		'can_invite_users',
		'can_pin_messages',
		'is_member',
		'can_send_messages',
		'can_send_media_messages',
		'can_send_polls',
		'can_send_other_messages',
		'can_add_web_page_previewes',
		'until_date'
	],
	#category : #'TPort-Types'
}
