Class {
	#name : #TPInlineQueryResultMpeg4Gif,
	#superclass : #TPInlineQueryResult,
	#instVars : [
		'type',
		'id',
		'mpeg4_url',
		'mpeg4_width',
		'mpeg4_height',
		'mpeg4_duration',
		'thumb_url',
		'thumb_mime_type',
		'title',
		'caption',
		'parse_mode',
		'caption_entites',
		'reply_markup',
		'input_message_content'
	],
	#category : #'TPort-InlineMode'
}

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> caption [
	^ caption
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> caption: anObject [
	caption := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> caption_entites [
	^ caption_entites
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> caption_entites: anObject [
	caption_entites := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> id [
	^ id
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> id: anObject [
	id := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> input_message_content [
	^ input_message_content
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> input_message_content: anObject [
	input_message_content := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_duration [
	^ mpeg4_duration
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_duration: anObject [
	mpeg4_duration := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_height [
	^ mpeg4_height
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_height: anObject [
	mpeg4_height := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_url [
	^ mpeg4_url
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_url: anObject [
	mpeg4_url := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_width [
	^ mpeg4_width
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> mpeg4_width: anObject [
	mpeg4_width := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> parse_mode [
	^ parse_mode
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> parse_mode: anObject [
	parse_mode := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> reply_markup [
	^ reply_markup
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> reply_markup: anObject [
	reply_markup := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> thumb_mime_type [
	^ thumb_mime_type
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> thumb_mime_type: anObject [
	thumb_mime_type := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> thumb_url [
	^ thumb_url
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> thumb_url: anObject [
	thumb_url := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> title [
	^ title
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> title: anObject [
	title := anObject
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> type [
	^ type
]

{ #category : #accessing }
TPInlineQueryResultMpeg4Gif >> type: anObject [
	type := anObject
]
