Class {
	#name : #TPInlineQueryResultCachedMpeg4Gif,
	#superclass : #TPInlineQueryResult,
	#instVars : [
		'type',
		'id',
		'mpeg4_file_id',
		'title',
		'caption',
		'parse_mode',
		'caption_entities',
		'reply_markup',
		'input_message_content'
	],
	#category : #'TPort-InlineMode'
}

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> caption1 [
	^ caption
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> caption1: anObject [
	caption := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> caption_entities1 [
	^ caption_entities
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> caption_entities1: anObject [
	caption_entities := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> id1 [
	^ id
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> id1: anObject [
	id := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> input_message_content1 [
	^ input_message_content
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> input_message_content1: anObject [
	input_message_content := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> mpeg4_file_id [
	^ mpeg4_file_id
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> mpeg4_file_id: anObject [
	mpeg4_file_id := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> parse_mode1 [
	^ parse_mode
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> parse_mode1: anObject [
	parse_mode := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> reply_markup1 [
	^ reply_markup
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> reply_markup1: anObject [
	reply_markup := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> title1 [
	^ title
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> title1: anObject [
	title := anObject
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> type1 [
	^ type
]

{ #category : #accessing }
TPInlineQueryResultCachedMpeg4Gif >> type1: anObject [
	type := anObject
]
